### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by mrwbsn** [obarcelonap/laravel-elixir-connect#1]
Hi, i got this error when i run gulp inside my laravel project.. i thought it was a typo but when i see on your examples it is same require syntax.

```
require('laravel-elixir-connect)(elixir);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

then i try

```
require('laravel-elixir-connect')(elixir);
```

the result is 

```
path.js:488
      throw new TypeError('Arguments to path.join must be strings');
            ^
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Function.<anonymous> (/home/mrwbsn/node_modules/laravel-elixir-connect/index.js:26:30)
    at Function.<anonymous> (/home/mrwbsn/Projects/ammossi/node_modules/laravel-elixir/index.js:43:18)
    at /home/mrwbsn/Projects/ammossi/gulpfile.js:18:9
    at Elixir (/home/mrwbsn/Projects/ammossi/node_modules/laravel-elixir/index.js:17:5)
    at Object.<anonymous> (/home/mrwbsn/Projects/ammossi/gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Thanks for making this great elixir plugin.

**Comment by JacekJagiello** [comment]
I have the same issue - it looks like this extension is not compatible with latest elixir 3.

**Comment by obarcelonap** [comment]
Hi there, I don't have time to upgrade it, send me a pull request if you solve it. Thank you
